### ISSUE TITLE
Add missing return type for UnicodeString implementation

### ISSUE THREAD

**Issue by matiux** [opis/string#3]
While upgrading to Symfony 5.4 I noticed the follow reported deprecations:

  1x: Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "Opis\String\UnicodeString" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Opis\String\UnicodeString" now to avoid errors or add an explicit @return annotation to suppress this message.
  
  Maybe it is enough to explicitly add void return type to the UnicodeString::offsetUnset() and UnicodeString::offsetSet() methods?

**Comment by sorinsarca** [comment]
Should be fixed by #2 in v2.0.1
